// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace WebApiFutLunes.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Naming : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Naming));
        
        string IMigrationMetadata.Id
        {
            get { return "201808070102377_Naming"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
